language: node_js
node_js:
  - 13

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
  - docker tag udagram-api-user bilinli/udagram-api-user:v1
  - docker tag udagram-api-feed bilinli/udagram-api-feed:v1
  - docker tag udagram-frontend bilinli/udagram-frontend:v1
  - docker tag reverseproxy bilinli/reverseproxy:v1
  - docker push bilinli/udagram-api-user:v1
  - docker push bilinli/udagram-api-feed:v1
  - docker push bilinli/udagram-frontend:v1
  - docker push bilinli/reverseproxy:v1