apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
spec:
  selector:
    service: udagram-frontend
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
      protocol: TCP